# Supabase Configuration

[api]
enabled = true
port = 54321

[auth]
enabled = true
site_url = "http://localhost:3000"
jwt_expiry = 3600
enable_signup = true

[db]
port = 54322
major_version = 15

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"

[inbucket]
enabled = true
port = 54324